trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'

pool:
  vmImage: $(operatingSystem)

stages:
  - stage: build
    jobs:
      - job: build job
        steps:
          - bash: echo "Do the build"
  - stage: Dev Deploy
    jobs:
      - deployment: DevDeployJob
        environment: Dev
        strategy:
         runOnce:
           deploy:
            steps:
              - script: echo deploy to dev
  - stage: QA Deploy
    jobs:
      - deployment: QADeployJob
        environment: QA
        strategy:
         runOnce:
           deploy:
            steps:
              - script: echo deploy to qa
